[project]
name = "cs-record-linkage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ftfy>=6.3.1",
    "fuzzywuzzy>=0.18.0",
    "python-levenshtein>=0.27.1",
    "recordlinkage>=0.16",
    "rich>=14.0.0",
]
